%This figure plots climate vars from MAR not included in a figure for the 
%paper Horlings et al. (2022), but that are referenced within the text.

%Author:Annika Horlings
%University of Washington
%Last updated: 10 May 2022

%% Load in the parameters
%These were already averaged of the area of interest
cd('/Users/annikahorlings/Documents/Projects/Greenland_Firn_Aquifer/Database_climate');
clim = load('climupstream.mat'); daysonset = clim.daysonset; 
datesmar = clim.datesmar; daysduration = clim.daysduration; 
count = clim.countabovehigh; rain = clim.rainsum;

%% Plotting
%This fig includes:
% -onset of melt
% -duration of melt
%- number of days above melt threshold
% - annual rainfall

fclim = figure;
cmap = intense(max(10));

%1 - melt onset
subplot(4, 1, 1); 
plot(datesmar, daysonset, '-', 'LineWidth', 2, 'Color', 'k', ...
    'MarkerFaceColor', 'k'); 
hold on;
[sddaysonset, mndecdaysonset, datesmean] = pltstats(daysonset, datesmar);
cdaysonset = findchangepts(daysonset, 'Statistic', 'mean');
for i = 1:length(mndecdaysonset)
    p = patch('vertices', [datesmean{i}(1), ...
        mndecdaysonset(i) - sddaysonset(i); datesmean{i}(1), ...
        mndecdaysonset(i) + sddaysonset(i); ...
        datesmean{i}(end)+1, mndecdaysonset(i) + sddaysonset(i); ...
        datesmean{i}(end)+1, mndecdaysonset(i) - sddaysonset(i)], ...
          'faces', [1, 2, 3, 4], ...
          'FaceColor', 'k', ...
          'FaceAlpha', 0.3, ...
          'EdgeColor', 'none');
end
ylabel('melt onset (d)'); 
ylim([min(daysonset) - 1   max(daysonset) + 1 ]);
xlim([1947.5 2016.5]);
set(gca,'XTickLabel',[]);
set(gca, 'LineWidth', 2);
set(gca, 'FontSize', 14);
grid on;
plot(datesmar, daysonset, '-', 'LineWidth', 2, 'Color', 'k', ...
    'MarkerFaceColor', 'k'); 
hold on;
plot(ones(1, 100).*datesmar(cdaysonset), ...
    linspace(min(daysonset) - 0.05, max(daysonset) + 0.05, 100), 'g');
hold on;
plot(linspace(datesmar(1), datesmar(cdaysonset), cdaysonset), ...
    ones(1, cdaysonset).*...
    mean(daysonset(1:cdaysonset)), 'r');
hold on;
plot(linspace(datesmar(cdaysonset), datesmar(end), ...
    length(daysonset) - cdaysonset), ...
    ones(1, length(daysonset)- ...
    cdaysonset).*mean(daysonset(cdaysonset:end)), 'r'); %plot, again

%2 - melt duration
subplot(4, 1, 2); 
plot(datesmar, daysduration, '-', 'LineWidth', 2, 'Color', 'k', ...
    'MarkerFaceColor', 'k'); 
hold on;
[sddaysduration, mndecdaysduration, datesmean] = ...
    pltstats(daysduration, datesmar); 
cdaysduration = findchangepts(daysduration, 'Statistic', 'mean');
for i = 1:length(mndecdaysduration)
    p = patch('vertices', [datesmean{i}(1), ...
        mndecdaysduration(i) - sddaysduration(i); ...
        datesmean{i}(1), mndecdaysduration(i) + sddaysduration(i); ...
        datesmean{i}(end)+1, mndecdaysduration(i) + sddaysduration(i); ...
        datesmean{i}(end)+1, mndecdaysduration(i) - sddaysduration(i)], ...
          'faces', [1, 2, 3, 4], ...
          'FaceColor', 'k', ...
          'FaceAlpha', 0.3, ...
          'EdgeColor', 'none');
end
ylabel('melt duration (d)'); 
xlim([1947.5 2016.5]);
ylim([min(daysduration) - 1  max(daysduration) + 1]);
set(gca,'XTickLabel',[]);
set(gca, 'LineWidth', 2);
set(gca, 'FontSize', 14);
grid on;
plot(datesmar, daysduration, '-', 'LineWidth', 2, 'Color', 'k', ...
    'MarkerFaceColor', 'k'); 
plot(ones(1, 100).*datesmar(cdaysduration), ...
    linspace(min(daysduration) - 0.05, max(daysduration) + 0.05, 100), 'g');
hold on;
plot(linspace(datesmar(1), datesmar(cdaysduration), ...
    cdaysduration), ones(1, ...
    cdaysduration).*mean(daysduration(1:cdaysduration)), 'r');
hold on;
plot(linspace(datesmar(cdaysduration), datesmar(end), ...
    length(daysduration) - cdaysduration), ...
    ones(1, length(daysduration)-...
    cdaysduration).*mean(daysduration(cdaysduration:end)), 'r'); %plot, again

%3 - melt duration
subplot(4, 1, 3); 
plot(datesmar, count, '-', 'LineWidth', 2, 'Color', 'k', ...
    'MarkerFaceColor', 'k'); 
hold on;
[sdcount, mndeccount, datesmean] = pltstats(count, datesmar); 
ccount = findchangepts(count, 'Statistic', 'mean');
for i = 1:length(mndeccount)
    p = patch('vertices', [datesmean{i}(1), mndeccount(i) - sdcount(i); ...
        datesmean{i}(1), mndeccount(i) + sdcount(i); ...
        datesmean{i}(end)+1, mndeccount(i) + sdcount(i); ...
        datesmean{i}(end)+1, mndeccount(i) - sdcount(i)], ...
          'faces', [1, 2, 3, 4], ...
          'FaceColor', 'k', ...
          'FaceAlpha', 0.3, ...
          'EdgeColor', 'none');
end
ylabel('melt count (d)'); 
xlim([1947.5 2016.5]);
ylim([min(count) - 1  max(count) + 1]);
set(gca, 'LineWidth', 2);
set(gca, 'FontSize', 14);
set(gca,'XTickLabel',[]);
grid on;
plot(datesmar, count, '-', 'LineWidth', 2, 'Color', 'k', ...
    'MarkerFaceColor', 'k'); 
hold on;
plot(ones(1, 100).*datesmar(ccount), linspace(min(count) - 0.05, ...
    max(count) + 0.05, 100), 'g');
hold on;
plot(linspace(datesmar(1), datesmar(ccount), ccount), ones(1, ccount).*...
    mean(count(1:ccount)), 'r');
hold on;
plot(linspace(datesmar(ccount), datesmar(end), length(count) - ccount), ...
    ones(1, length(count)-ccount).*mean(count(ccount:end)), 'r');%plot, again

%4 - rain
subplot(4, 1, 4);
plot(datesmar, rain, '-', 'LineWidth', 2, 'Color', 'k', ...
    'MarkerFaceColor', 'k'); 
hold on;
[sdrain, mndecrain, datesmean] = pltstats(rain, datesmar); 
crain = findchangepts(rain, 'Statistic', 'mean');
for i = 1:length(mndecrain)
    p = patch('vertices', [datesmean{i}(1), mndecrain(i) - sdrain(i); ...
        datesmean{i}(1), mndecrain(i) + sdrain(i); ...
        datesmean{i}(end)+1, mndecrain(i) + sdrain(i); ...
        datesmean{i}(end)+1, mndecrain(i) - sdrain(i)], ...
          'faces', [1, 2, 3, 4], ...
          'FaceColor', 'k', ...
          'FaceAlpha', 0.3, ...
          'EdgeColor', 'none');
end
xlabel('year');
ylabel('annual rainfall (mm)'); 
set(gca, 'LineWidth', 2);
set(gca, 'FontSize', 14);
xlim([1947.5 2016.5]);
ylim([min(rain) - 15  max(rain) + 2]);
grid on;
plot(datesmar, rain, '-', 'LineWidth', 2, 'Color', 'k', ...
    'MarkerFaceColor', 'k'); 
hold on;
plot(ones(1, 100).*datesmar(crain), linspace(min(rain) - 0.05, ...
    max(rain) + 0.05, 100), 'Color', [0 153/255 153/255]);
hold on;
plot(linspace(datesmar(1), datesmar(crain), crain), ones(1, crain).*...
    mean(rain(1:crain)), 'Color', [204/255 102/255 0]);
hold on;
plot(linspace(datesmar(crain), datesmar(end), length(rain) - crain), ...
    ones(1, length(rain)-crain).*mean(rain(crain:end)), ...
'Color', [204/255 102/255 0]);

%set figure position and size
set(fclim, 'Position', [560   320   726   628]);

